version: '3'

services:

  db:
    image: mariadb:latest
    volumes:
      - prestashop_dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: prestashop

  prestashop:
    image: prestashop/prestashop:1.6
    depends_on:
      - db
    ports:
      - "8082:80"
    environment:
      PS_DEV_MODE: 1 # The constant _PS_MODE_DEV_ will be set at true (default value: 0)
      # PS_HOST_MODE: The constant _PS_HOST_MODE_ will be set at true. Useful to simulate a PrestaShop Cloud environment. (default value: 0)
      # PS_DEMO_MODE: 0 # The constant _PS_DEMO_MODE_ will be set at true. Use it to create a demonstration shop. (default value: 0)
      DB_SERVER: db # If set, the external MySQL database will be used instead of the volatile internal one (default value: localhost)
      # DB_USER: Override default MySQL user (default value: root)
      # DB_PASSWD: admin # Override default MySQL password (default value: admin)
      # DB_PREFIX: Override default tables prefix (default value: ps_)
      # DB_NAME: Override default database name (default value: prestashop)
      PS_INSTALL_AUTO: 1 # The installation will be executed. Useful to initialize your image faster. In some configurations, you may need to set PS_DOMAIN or PS_HANDLE_DYNAMIC_DOMAIN as well. (Please note that PrestaShop can be installed automatically from PS 1.5)
      PS_ERASE_DB: 0 # Only with PS_INSTALL_AUTO=1. Drop and create the mysql database. All previous mysql data will be lost (default value: 0)
      PS_DOMAIN: localhost:8082 # When installing automatically your shop, you can tell the shop how it will be reached. For advanced users only (no default value)
      PS_LANGUAGE: fr # Change the default language installed with PrestaShop (default value: en)
      PS_COUNTRY: FR # Change the default country installed with PrestaShop (default value: GB)
      # PS_ALL_LANGUAGES: Install all the existing languages for the current version. (default value: 0)
      PS_FOLDER_ADMIN: admin-dev # Change the name of the admin folder (default value: admin. But will be automatically changed later)
      # PS_FOLDER_INSTALL: Change the name of the install folder (default value: install. But must be changed anyway later)
      # PS_ENABLE_SSL: Enable SSL at PrestaShop installation. (default value: 0)
    volumes:
      - ./prestashop:/var/www/html/modules/coopcycle
      # Add a volume for config files so that PrestaShop is not reinstalled every time
      # https://github.com/PrestaShop/docker/issues/105
      - prestashop_config:/var/www/html/config

volumes:
  prestashop_dbdata:
  prestashop_config:

networks:
  default:
    external:
      name: coopcycle-web_default
