# https://github.com/chriszarate/docker-compose-wordpress
# https://github.com/WordPress/gutenberg/blob/master/docker-compose.yml

version: '3.3'

services:

  db:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    image: wordpress:latest
    depends_on:
      - db
    ports:
      - "9000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    volumes:
      - wordpress:/var/www/html
      - .:/var/www/html/wp-content/plugins/coopcycle

  wp:
    image: wordpress:cli
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
      - .:/var/www/html/wp-content/plugins/coopcycle

volumes:
  dbdata:
  wordpress:
